$items = [
    (object)[
        'id' => 1,
        'name' => 'Dell Inspiron 15',
        'code' => 'LPT001',
        'Quantity' => 25,
        'stock_status' => 'in_stock',
        'image_path' => 'item_images/dell_inspiron.jpg',
        'description' => 'Dell Inspiron 15 5000 series with 8GB RAM and 512GB SSD.',
    ],
    (object)[
        'id' => 2,
        'name' => 'Apple iPhone 14',
        'code' => 'MBL002',
        'Quantity' => 50,
        'stock_status' => 'in_stock',
        'image_path' => 'item_images/iphone_14.jpg',
        'description' => 'Apple iPhone 14, 128GB, Midnight color.',
    ],
    (object)[
        'id' => 3,
        'name' => 'Sony WH-1000XM5',
        'code' => 'HDPH003',
        'Quantity' => 15,
        'stock_status' => 'out_of_stock',
        'image_path' => 'item_images/sony_headphones.jpg',
        'description' => 'Sony wireless noise-cancelling over-ear headphones.',
    ],
    (object)[
        'id' => 4,
        'name' => 'Samsung Galaxy S23',
        'code' => 'MBL004',
        'Quantity' => 30,
        'stock_status' => 'in_stock',
        'image_path' => 'item_images/galaxy_s23.jpg',
        'description' => 'Samsung Galaxy S23, 256GB, Phantom Black.',
    ],
    (object)[
        'id' => 5,
        'name' => 'HP LaserJet Pro',
        'code' => 'PRN005',
        'Quantity' => 10,
        'stock_status' => 'out_of_stock',
        'image_path' => 'item_images/hp_printer.jpg',
        'description' => 'HP LaserJet Pro MFP M428fdw, monochrome printer.',
    ],
];
